<?php
/**
 * Plugin Name: Manajemen Umroh Hybrid
 * Description: Sistem Manajemen Travel Umroh Enterprise (React + WP REST API).
 * Version: 4.0.4
 * Author: Bonang Panji Nur
 * Text Domain: umroh-manager
 */

if ( ! defined( 'ABSPATH' ) ) {
    exit;
}

// 1. Definisi Konstanta Path
define( 'UMH_PLUGIN_DIR', plugin_dir_path( __FILE__ ) );
define( 'UMH_PLUGIN_URL', plugin_dir_url( __FILE__ ) );

// 2. Include File-File Penting (URUTAN SANGAT PENTING)
// -----------------------------------------------------

// A. Utils & Helper (Muat duluan agar fungsinya bisa dipakai file lain)
if ( file_exists( UMH_PLUGIN_DIR . 'includes/utils.php' ) ) {
    require_once UMH_PLUGIN_DIR . 'includes/utils.php';
}

// B. Database Schema
require_once UMH_PLUGIN_DIR . 'includes/db-schema.php';

// C. Security & CORS
if ( file_exists( UMH_PLUGIN_DIR . 'includes/cors.php' ) ) {
    require_once UMH_PLUGIN_DIR . 'includes/cors.php';
}

// D. Admin Customizer (Login Page, Footer, etc)
if ( file_exists( UMH_PLUGIN_DIR . 'includes/admin-login-customizer.php' ) ) {
    require_once UMH_PLUGIN_DIR . 'includes/admin-login-customizer.php';
}

// E. API & Controller Loader
require_once UMH_PLUGIN_DIR . 'includes/class-umh-api-loader.php';


// 3. Hook Aktivasi (Buat Tabel Database)
register_activation_hook( __FILE__, 'umh_activate_plugin' );
function umh_activate_plugin() {
    umh_create_db_tables();
}

// 4. Init API Loader (Saat Plugin Dimuat)
function umh_init_api() {
    $loader = new UMH_API_Loader();
    $loader->init();
}
add_action( 'plugins_loaded', 'umh_init_api' );

// 5. Daftarkan Menu Admin
function umh_add_admin_menu() {
    add_menu_page(
        'Manajemen Umroh',      // Page Title
        'Manajemen Umroh',      // Menu Title
        'manage_options',       // Capability
        'umroh-manager',        // Menu Slug
        'umh_render_react_page',// Callback Function
        'dashicons-airplane',   // Icon
        2                       // Position
    );
}
add_action( 'admin_menu', 'umh_add_admin_menu' );

// Callback untuk merender halaman (Memanggil file wadah)
function umh_render_react_page() {
    require_once UMH_PLUGIN_DIR . 'admin/dashboard-react.php';
}

// 6. Enqueue Scripts & Styles (Menghubungkan React Build)
function umh_enqueue_admin_scripts( $hook ) {
    // Hanya load di halaman plugin kita agar tidak bentrok dengan plugin lain
    if ( $hook !== 'toplevel_page_umroh-manager' ) {
        return;
    }

    // Cek keberadaan file asset (generated by build)
    $asset_file_path = UMH_PLUGIN_DIR . 'build/index.asset.php';
    
    if ( ! file_exists( $asset_file_path ) ) {
        // Fallback jika belum di-build, gunakan default
        $asset_file = array( 'dependencies' => array( 'wp-element', 'wp-polyfill' ), 'version' => '1.0.0' );
    } else {
        $asset_file = include( $asset_file_path );
    }

    // Load CSS Aplikasi
    wp_enqueue_style(
        'umroh-manager-style',
        UMH_PLUGIN_URL . 'build/index.css',
        array(),
        $asset_file['version']
    );

    // Load JS Aplikasi (React)
    wp_enqueue_script(
        'umroh-manager-react',
        UMH_PLUGIN_URL . 'build/index.js',
        $asset_file['dependencies'],
        $asset_file['version'],
        true // Load di footer
    );

    // Kirim Data Konfigurasi ke React (Global Variable: umhData)
    // React bisa akses ini via window.umhData
    wp_localize_script( 'umroh-manager-react', 'umhData', array(
        'root_url' => esc_url_raw( rest_url() ),
        'nonce'    => wp_create_nonce( 'wp_rest' ),
        'admin_url'=> admin_url(),
        'user_id'  => get_current_user_id(),
        'site_name'=> get_bloginfo( 'name' )
    ) );
}
add_action( 'admin_enqueue_scripts', 'umh_enqueue_admin_scripts' );